// src/lib/blocks/Footer.svelte
<script lang="ts">
    import Body from "$lib/components/Body.svelte";
	import Link from "$lib/components/Link.svelte";
</script>

<footer class="container">
	<Body>
		<div class="wrapper">
			<span class="copyright">
				&copy; {new Date().getFullYear()}
				<Link to="https://heyjes.dev/">Joshua Elijah Sandoval.</Link>
			</span>
			<span>
				<ul class="about">
					<li><Link to="https://github.com/JoshuaSand0val/semantic-props/">Github</Link></li>
					<li class="version">v2.0.0-beta.0 (MIT)</li>
				</ul>
				<Link to="#top">Scroll to Top ↑</Link>
			</span>
		</div>
	</Body>
</footer>

<style>
	.container {
		display: block;
		border-block-start: 1px var(--border-style) var(--secondary-color);
	}

	.wrapper {
		display: flex;
		flex-flow: row wrap;
		align-items: start;
		justify-content: space-between;
		font-size: var(--small);
		color: var(--low-contrast-color);
		gap: var(--3x-small) 1ch;
		margin-inline: auto;
		margin-bottom: var(--safe-bottom);
		overflow: hidden;
	}

	.about {
		display: flex;
		flex-flow: row wrap;
		padding: 0;
		margin: 0;
		li {
			list-style: inside;
			margin-inline-start: 1ch;
			&:first-child {
				list-style-type: none;
				margin-inline-start: 0;
			}
		}
	}
</style>

// src/components/Footer.tsx
import "./Footer.css";
import Link from "./Link";

export default function Footer() {
	return (
		<footer className="Footer container">
				<div className="wrapper">
					<span className="copyright">
						&copy; {new Date().getFullYear()}{" "}
						<Link to="https://heyjes.dev/">Joshua Elijah Sandoval.</Link>
					</span>
					<span className="info">
						<Link to="https://github.com/JoshuaSand0val/semantic-props/">Github</Link> &mdash;
						v2.0.0-beta.0 (MIT)
					</span>
				</div>
		</footer>
	);
}
